version: '3.9'
services:
  docker-frontend: 
    build:
      context: MyAccess_Property
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    volumes:
      - ./MyAccess_Property/src:/frontend/src
  

    
  json-backend: 
    build:
      context: json-server
      dockerfile: Dockerfile
    volumes:
      - ./json-server:/backend/
    
     