version: '3.9'
services:
  docker-frontend: 
    build:
      context: MyAccess_Property
      dockerfile: Dockerfile.dev
    ports:
      - '3004:3004'
    volumes:
      - ./MyAccess_Property/src:/frontend/src
    depends_on:
      - docker-backend

    
  docker-backend: 
    build:
      context: json-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./json-server:/backend/
    depends_on:
      - docker-frontend
     